// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToeicWeb.ExamService.ExamService.Data;

#nullable disable

namespace ExamService.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20241102161541_dbinit")]
    partial class dbinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestionID");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = false,
                            QuestionID = 1,
                            Text = "He is eating"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = true,
                            QuestionID = 1,
                            Text = "He is talking on the phone"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionID = 1,
                            Text = "He is walking"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionID = 1,
                            Text = "He is reading"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            QuestionID = 2,
                            Text = "In a conference room"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionID = 2,
                            Text = "In a cafe"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuestionID = 2,
                            Text = "In a park"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionID = 2,
                            Text = "At the airport"
                        });
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<int>("Total_Listening")
                        .HasColumnType("int");

                    b.Property<int>("Total_Reading")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestID");

                    b.ToTable("history", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4091),
                            StartTime = new DateTime(2024, 11, 2, 21, 15, 41, 495, DateTimeKind.Local).AddTicks(4086),
                            TestID = 1,
                            Total_Listening = 75,
                            Total_Reading = 80,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4094),
                            StartTime = new DateTime(2024, 11, 2, 21, 15, 41, 495, DateTimeKind.Local).AddTicks(4093),
                            TestID = 2,
                            Total_Listening = 85,
                            Total_Reading = 90,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.HistoryDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HistoryID")
                        .HasColumnType("int");

                    b.Property<int>("PartID")
                        .HasColumnType("int");

                    b.Property<int>("TotalCorrect")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistoryID");

                    b.HasIndex("PartID");

                    b.ToTable("historydetail", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HistoryID = 1,
                            PartID = 1,
                            TotalCorrect = 8,
                            TotalQuestion = 10
                        },
                        new
                        {
                            Id = 2,
                            HistoryID = 1,
                            PartID = 2,
                            TotalCorrect = 7,
                            TotalQuestion = 10
                        },
                        new
                        {
                            Id = 3,
                            HistoryID = 2,
                            PartID = 3,
                            TotalCorrect = 9,
                            TotalQuestion = 10
                        },
                        new
                        {
                            Id = 4,
                            HistoryID = 2,
                            PartID = 4,
                            TotalCorrect = 6,
                            TotalQuestion = 10
                        });
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TestID");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3986),
                            Description = "Listening Comprehension",
                            Name = "Part 1",
                            Number = 1,
                            TestID = 1,
                            UpdatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3987)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3989),
                            Description = "Reading Comprehension",
                            Name = "Part 2",
                            Number = 2,
                            TestID = 1,
                            UpdatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3989)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3990),
                            Description = "Listening Comprehension",
                            Name = "Part 1",
                            Number = 1,
                            TestID = 2,
                            UpdatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3991)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4016),
                            Description = "Reading Comprehension",
                            Name = "Part 2",
                            Number = 2,
                            TestID = 2,
                            UpdatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4016)
                        });
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerCounts")
                        .HasColumnType("int");

                    b.Property<string>("AudioName")
                        .HasColumnType("longtext");

                    b.Property<string>("AudioPath")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageName")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<int>("PartID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PartID");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerCounts = 4,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4040),
                            PartID = 1,
                            Text = "What is he doing?",
                            UpdatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4040)
                        },
                        new
                        {
                            Id = 2,
                            AnswerCounts = 4,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4042),
                            PartID = 1,
                            Text = "Where is he going?",
                            UpdatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4043)
                        },
                        new
                        {
                            Id = 3,
                            AnswerCounts = 4,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4044),
                            PartID = 2,
                            Text = "What does the sign say?",
                            UpdatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4045)
                        },
                        new
                        {
                            Id = 4,
                            AnswerCounts = 4,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4046),
                            PartID = 2,
                            Text = "What is the main idea of the passage?",
                            UpdatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(4046)
                        });
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3821),
                            Description = "Mô tả bài kiểm tra 1",
                            Difficulty = "Easy",
                            Duration = 60,
                            Name = "Test 1",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3837),
                            Description = "Mô tả bài kiểm tra 2",
                            Difficulty = "Medium",
                            Duration = 75,
                            Name = "Test 2",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 2, 23, 15, 41, 495, DateTimeKind.Local).AddTicks(3839),
                            Description = "Mô tả bài kiểm tra 3",
                            Difficulty = "Hard",
                            Duration = 90,
                            Name = "Test 3",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HistoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("SelectedAnswerID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistoryID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SelectedAnswerID");

                    b.ToTable("UserAnswers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HistoryID = 1,
                            IsCorrect = true,
                            QuestionID = 1,
                            SelectedAnswerID = 2,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            HistoryID = 1,
                            IsCorrect = true,
                            QuestionID = 2,
                            SelectedAnswerID = 5,
                            UserID = 1
                        },
                        new
                        {
                            Id = 3,
                            HistoryID = 2,
                            IsCorrect = true,
                            QuestionID = 3,
                            SelectedAnswerID = 11,
                            UserID = 2
                        },
                        new
                        {
                            Id = 4,
                            HistoryID = 2,
                            IsCorrect = true,
                            QuestionID = 4,
                            SelectedAnswerID = 15,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.Answer", b =>
                {
                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.History", b =>
                {
                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.Test", null)
                        .WithMany()
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.HistoryDetail", b =>
                {
                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.History", null)
                        .WithMany()
                        .HasForeignKey("HistoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.Part", null)
                        .WithMany()
                        .HasForeignKey("PartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.Part", b =>
                {
                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.Test", null)
                        .WithMany()
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.Question", b =>
                {
                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.Part", null)
                        .WithMany()
                        .HasForeignKey("PartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicWeb.ExamService.ExamService.Models.UserAnswer", b =>
                {
                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.History", null)
                        .WithMany()
                        .HasForeignKey("HistoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicWeb.ExamService.ExamService.Models.Answer", null)
                        .WithMany()
                        .HasForeignKey("SelectedAnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
