services:
  examservice:
    image: ${DOCKER_REGISTRY-}examservice
    build:
      context: .
      dockerfile: ExamService/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - toeicdb

  toeicdb:
    image: mysql:8.0
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_DATABASE: toeicweb
       MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
